CHAINS = [
    {
        "chain_code": "btc",
        "shortname": "BTC",
        "fee_coin": "btc",
        "name": "Bitcoin",
        "chain_model": "utxo",
        "curve": "secp256k1",
        "chain_affinity": "btc",
        "qr_code_prefix": "bitcoin",
        "bip44_coin_type": 0,
        "bip44_last_hardened_level": "ACCOUNT",
        "bip44_auto_increment_level": "ACCOUNT",
        "bip44_target_level": "ADDRESS_INDEX",
        "default_address_encoding": "P2WPKH-P2SH",
        "chain_id": None,
        "bip44_purpose_options": {"P2PKH": 44, "P2WPKH-P2SH": 49, "P2WPKH": 84},
        "fee_price_decimals_for_legibility": 0,
        "nonce_supported": False,
        "dust_threshold": 546,
        "blocktime_seconds": 600,
        "coins": [
            {
                "code": "btc",
                "symbol": "BTC",
                "name": "Bitcoin",
                "decimals": 8,
                "icon": "https://onekey.243096.com/onekey/images/token/btc/BTC.png",
            }
        ],
        "clients": [
            {"class": "BlockBook", "url": "https://btc1.trezor.io"},
            {"class": "BlockBook", "url": "https://btc2.trezor.io"},
            {"class": "BlockBook", "url": "https://btc3.trezor.io"},
            {"class": "BlockBook", "url": "https://btc4.trezor.io"},
            {"class": "BlockBook", "url": "https://btc5.trezor.io"},
        ],
    },
    {
        "chain_code": "bch",
        "shortname": "BCH",
        "fee_coin": "bch",
        "name": "Bcash",
        "chain_model": "utxo",
        "curve": "secp256k1",
        "chain_affinity": "bch",
        "qr_code_prefix": "BitcoinCash",
        "bip44_coin_type": 145,
        "bip44_last_hardened_level": "ACCOUNT",
        "bip44_auto_increment_level": "ACCOUNT",
        "bip44_target_level": "ADDRESS_INDEX",
        "default_address_encoding": "P2PKH",
        "bip44_purpose_options": {},
        "chain_id": None,
        "fee_price_decimals_for_legibility": 0,
        "nonce_supported": False,
        "dust_threshold": 546,
        "blocktime_seconds": 600,
        "coins": [
            {
                "code": "bch",
                "symbol": "BCH",
                "name": "Bitcoin Cash",
                "decimals": 8,
                "icon": "https://onekey.243096.com/onekey/images/token/btc/BTC.png",
            }
        ],
        "clients": [
            {"class": "BlockBook", "url": "https://bch1.trezor.io"},
            {"class": "BlockBook", "url": "https://bch2.trezor.io"},
            {"class": "BlockBook", "url": "https://bch3.trezor.io"},
            {"class": "BlockBook", "url": "https://bch4.trezor.io"},
            {"class": "BlockBook", "url": "https://bch5.trezor.io"},
        ],
    },
    {
        "chain_code": "ltc",
        "shortname": "LTC",
        "fee_coin": "ltc",
        "name": "Litecoin",
        "chain_model": "utxo",
        "curve": "secp256k1",
        "chain_affinity": "btc",
        "qr_code_prefix": "Litecoin",
        "bip44_coin_type": 2,
        "bip44_last_hardened_level": "ACCOUNT",
        "bip44_auto_increment_level": "ACCOUNT",
        "bip44_target_level": "ADDRESS_INDEX",
        "default_address_encoding": "P2WPKH-P2SH",
        "chain_id": None,
        "bip44_purpose_options": {"P2PKH": 44, "P2WPKH-P2SH": 49, "P2WPKH": 84},
        "fee_price_decimals_for_legibility": 0,
        "nonce_supported": False,
        "dust_threshold": 546,
        "blocktime_seconds": 150,
        "coins": [
            {
                "code": "ltc",
                "symbol": "LTC",
                "name": "Litecoin",
                "decimals": 8,
                "icon": "http  s://onekey.243096.com/onekey/images/token/btc/BTC.png",
            }
        ],
        "clients": [
            {"class": "BlockBook", "url": "https://ltc1.trezor.io"},
            {"class": "BlockBook", "url": "https://ltc2.trezor.io"},
            {"class": "BlockBook", "url": "https://ltc3.trezor.io"},
            {"class": "BlockBook", "url": "https://ltc4.trezor.io"},
            {"class": "BlockBook", "url": "https://ltc5.trezor.io"},
        ],
    },
    {
        "chain_code": "doge",
        "shortname": "DOGE",
        "fee_coin": "doge",
        "name": "Dogecoin",
        "chain_model": "utxo",
        "curve": "secp256k1",
        "chain_affinity": "btc",
        "qr_code_prefix": "Dogecoin",
        "bip44_coin_type": 3,
        "bip44_last_hardened_level": "ACCOUNT",
        "bip44_auto_increment_level": "ACCOUNT",
        "bip44_target_level": "ADDRESS_INDEX",
        "default_address_encoding": "P2PKH",
        "bip44_purpose_options": {},
        "chain_id": None,
        "fee_price_decimals_for_legibility": 0,
        "nonce_supported": False,
        "dust_threshold": 99999999,
        "blocktime_seconds": 60,
        "coins": [
            {
                "code": "doge",
                "symbol": "Doge",
                "name": "Dogecoin",
                "decimals": 8,
                "icon": "https://onekey.243096.com/onekey/images/token/btc/BTC.png",
            }
        ],
        "clients": [
            {"class": "BlockBook", "url": "https://doge1.trezor.io"},
            {"class": "BlockBook", "url": "https://doge2.trezor.io"},
            {"class": "BlockBook", "url": "https://doge3.trezor.io"},
            {"class": "BlockBook", "url": "https://doge4.trezor.io"},
            {"class": "BlockBook", "url": "https://doge5.trezor.io"},
        ],
    },
    {
        "chain_code": "dash",
        "shortname": "DASH",
        "fee_coin": "dash",
        "name": "Dash",
        "chain_model": "utxo",
        "curve": "secp256k1",
        "chain_affinity": "btc",
        "qr_code_prefix": "Dash",
        "bip44_coin_type": 5,
        "bip44_last_hardened_level": "ACCOUNT",
        "bip44_auto_increment_level": "ACCOUNT",
        "bip44_target_level": "ADDRESS_INDEX",
        "default_address_encoding": "P2PKH",
        "bip44_purpose_options": {},
        "chain_id": None,
        "fee_price_decimals_for_legibility": 0,
        "nonce_supported": False,
        "dust_threshold": 5460,
        "blocktime_seconds": 150,
        "coins": [
            {
                "code": "dash",
                "symbol": "DASH",
                "name": "Dash",
                "decimals": 8,
                "icon": "https://onekey.243096.com/onekey/images/token/btc/BTC.png",
            }
        ],
        "clients": [
            {"class": "BlockBook", "url": "https://dash1.trezor.io"},
            {"class": "BlockBook", "url": "https://dash2.trezor.io"},
            {"class": "BlockBook", "url": "https://dash3.trezor.io"},
            {"class": "BlockBook", "url": "https://dash4.trezor.io"},
            {"class": "BlockBook", "url": "https://dash5.trezor.io"},
        ],
    },
    {
        "chain_code": "zec",
        "shortname": "ZEC",
        "fee_coin": "zec",
        "name": "Zcash",
        "chain_model": "utxo",
        "curve": "secp256k1",
        "chain_affinity": "btc",
        "qr_code_prefix": "Zcash",
        "bip44_coin_type": 133,
        "bip44_last_hardened_level": "ACCOUNT",
        "bip44_auto_increment_level": "ACCOUNT",
        "bip44_target_level": "ADDRESS_INDEX",
        "default_address_encoding": "P2PKH",
        "bip44_purpose_options": {},
        "chain_id": None,
        "fee_price_decimals_for_legibility": 0,
        "nonce_supported": False,
        "dust_threshold": 546,
        "blocktime_seconds": 150,
        "coins": [
            {
                "code": "zec",
                "symbol": "ZEC",
                "name": "Zcash",
                "decimals": 8,
                "icon": "https://onekey.243096.com/onekey/images/token/btc/BTC.png",
            }
        ],
        "clients": [
            {"class": "BlockBook", "url": "https://zec1.trezor.io"},
            {"class": "BlockBook", "url": "https://zec2.trezor.io"},
            {"class": "BlockBook", "url": "https://zec3.trezor.io"},
            {"class": "BlockBook", "url": "https://zec4.trezor.io"},
            {"class": "BlockBook", "url": "https://zec5.trezor.io"},
        ],
    },
    {
        "chain_code": "btg",
        "shortname": "BTG",
        "fee_coin": "btg",
        "name": "Bgold",
        "chain_model": "utxo",
        "curve": "secp256k1",
        "chain_affinity": "btc",
        "qr_code_prefix": "BitcoinGold",
        "bip44_coin_type": 156,
        "bip44_last_hardened_level": "ACCOUNT",
        "bip44_auto_increment_level": "ACCOUNT",
        "bip44_target_level": "ADDRESS_INDEX",
        "default_address_encoding": "P2WPKH-P2SH",
        "chain_id": None,
        "bip44_purpose_options": {"P2PKH": 44, "P2WPKH-P2SH": 49, "P2WPKH": 84},
        "fee_price_decimals_for_legibility": 0,
        "nonce_supported": False,
        "dust_threshold": 546,
        "blocktime_seconds": 600,
        "coins": [
            {
                "code": "btg",
                "symbol": "BTG",
                "name": "Bitcoin Gold",
                "decimals": 8,
                "icon": "https://onekey.243096.com/onekey/images/token/btc/BTC.png",
            }
        ],
        "clients": [
            {"class": "BlockBook", "url": "https://btg1.trezor.io"},
            {"class": "BlockBook", "url": "https://btg2.trezor.io"},
            {"class": "BlockBook", "url": "https://btg3.trezor.io"},
            {"class": "BlockBook", "url": "https://btg4.trezor.io"},
            {"class": "BlockBook", "url": "https://btg5.trezor.io"},
        ],
    },
    {
        "chain_code": "dgb",
        "shortname": "DGB",
        "fee_coin": "dgb",
        "name": "DigiByte",
        "chain_model": "utxo",
        "curve": "secp256k1",
        "chain_affinity": "btc",
        "qr_code_prefix": "DigiByte",
        "bip44_coin_type": 20,
        "bip44_last_hardened_level": "ACCOUNT",
        "bip44_auto_increment_level": "ACCOUNT",
        "bip44_target_level": "ADDRESS_INDEX",
        "default_address_encoding": "P2WPKH-P2SH",
        "chain_id": None,
        "bip44_purpose_options": {"P2PKH": 44, "P2WPKH-P2SH": 49, "P2WPKH": 84},
        "fee_price_decimals_for_legibility": 0,
        "nonce_supported": False,
        "dust_threshold": 546,
        "blocktime_seconds": 15,
        "coins": [
            {
                "code": "dgb",
                "symbol": "DGB",
                "name": "DigiByte",
                "decimals": 8,
                "icon": "https://onekey.243096.com/onekey/images/token/btc/BTC.png",
            }
        ],
        "clients": [
            {"class": "BlockBook", "url": "https://dgb1.trezor.io"},
            {"class": "BlockBook", "url": "https://dgb2.trezor.io"},
        ],
    },
    {
        "chain_code": "nmc",
        "shortname": "NMC",
        "fee_coin": "nmc",
        "name": "Namecoin",
        "chain_model": "utxo",
        "curve": "secp256k1",
        "chain_affinity": "btc",
        "qr_code_prefix": "Namecoin",
        "bip44_coin_type": 7,
        "bip44_last_hardened_level": "ACCOUNT",
        "bip44_auto_increment_level": "ACCOUNT",
        "bip44_target_level": "ADDRESS_INDEX",
        "default_address_encoding": "P2PKH",
        "bip44_purpose_options": {},
        "chain_id": None,
        "fee_price_decimals_for_legibility": 0,
        "nonce_supported": False,
        "dust_threshold": 546,
        "blocktime_seconds": 600,
        "coins": [
            {
                "code": "nmc",
                "symbol": "NMC",
                "name": "Namecoin",
                "decimals": 8,
                "icon": "https://onekey.243096.com/onekey/images/token/btc/BTC.png",
            }
        ],
        "clients": [
            {"class": "BlockBook", "url": "https://nmc1.trezor.io"},
            {"class": "BlockBook", "url": "https://nmc2.trezor.io"},
        ],
    },
    {
        "chain_code": "vtc",
        "shortname": "VTC",
        "fee_coin": "vtc",
        "name": "Vertcoin",
        "chain_model": "utxo",
        "curve": "secp256k1",
        "chain_affinity": "btc",
        "qr_code_prefix": "Vertcoin",
        "bip44_coin_type": 28,
        "bip44_last_hardened_level": "ACCOUNT",
        "bip44_auto_increment_level": "ACCOUNT",
        "bip44_target_level": "ADDRESS_INDEX",
        "default_address_encoding": "P2WPKH-P2SH",
        "chain_id": None,
        "bip44_purpose_options": {"P2PKH": 44, "P2WPKH-P2SH": 49, "P2WPKH": 84},
        "fee_price_decimals_for_legibility": 0,
        "nonce_supported": False,
        "dust_threshold": 54600,
        "blocktime_seconds": 150,
        "coins": [
            {
                "code": "vtc",
                "symbol": "VTC",
                "name": "Vertcoin",
                "decimals": 8,
                "icon": "https://onekey.243096.com/onekey/images/token/btc/BTC.png",
            }
        ],
        "clients": [
            {"class": "BlockBook", "url": "https://vtc1.trezor.io"},
            {"class": "BlockBook", "url": "https://vtc2.trezor.io"},
            {"class": "BlockBook", "url": "https://vtc3.trezor.io"},
            {"class": "BlockBook", "url": "https://vtc4.trezor.io"},
            {"class": "BlockBook", "url": "https://vtc5.trezor.io"},
        ],
    },
    {
        "chain_code": "eth",
        "shortname": "ETH",
        "fee_coin": "eth",
        "name": "Ethereum",
        "chain_model": "account",
        "curve": "secp256k1",
        "chain_affinity": "eth",
        "qr_code_prefix": "ethereum",
        "bip44_coin_type": 60,
        "bip44_last_hardened_level": "ACCOUNT",
        "bip44_auto_increment_level": "ADDRESS_INDEX",
        "bip44_target_level": "ADDRESS_INDEX",
        "default_address_encoding": None,
        "chain_id": "1",
        "bip44_purpose_options": {},
        "fee_price_decimals_for_legibility": 9,
        "nonce_supported": True,
        "coins": [
            {
                "code": "eth",
                "symbol": "ETH",
                "name": "Ethereum",
                "decimals": 18,
                "icon": "https://onekey.243096.com/onekey/images/token/eth/ETH.png",
            }
        ],
        "clients": [
            {"class": "Geth", "url": "https://rpc.blkdb.cn/eth"},
            {"class": "Geth", "url": "https://eth1.onekey.so/rpc"},
            {"class": "BlockBook", "url": "https://eth1.onekey.so"},
            {"class": "BlockBook", "url": "https://eth1.trezor.io"},
            {
                "class": "Etherscan",
                "url": "https://api-cn.etherscan.com",
                "api_keys": ["R796P9T31MEA24P8FNDZBCA88UHW8YCNVW"],
            },
            {
                "class": "Etherscan",
                "url": "https://api.etherscan.io",
                "api_keys": ["R796P9T31MEA24P8FNDZBCA88UHW8YCNVW"],
            },
        ],
    },
    {
        "chain_code": "bsc",
        "shortname": "BSC",
        "fee_coin": "bsc",
        "name": "Binance Smart Chain",
        "chain_model": "account",
        "curve": "secp256k1",
        "chain_affinity": "eth",
        "qr_code_prefix": "bsc",
        "bip44_coin_type": 60,
        "bip44_last_hardened_level": "ACCOUNT",
        "bip44_auto_increment_level": "ADDRESS_INDEX",
        "bip44_target_level": "ADDRESS_INDEX",
        "default_address_encoding": None,
        "chain_id": "56",
        "bip44_purpose_options": {},
        "fee_price_decimals_for_legibility": 9,
        "nonce_supported": True,
        "coins": [
            {
                "code": "bsc",
                "symbol": "BNB",
                "name": "Binance Smart Chain",
                "decimals": 18,
                "icon": "https://onekey.243096.com/onekey/images/token/bsc/BSC.png",
            }
        ],
        "clients": [
            {"class": "Geth", "url": "https://rpc.blkdb.cn/bsc"},
            {"class": "Geth", "url": "https://bsc1.onekey.so/rpc"},
            {"class": "Geth", "url": "https://bsc-dataseed1.binance.org"},
            {"class": "BlockBook", "url": "https://bsc1.onekey.so"},
            {
                "class": "Etherscan",
                "url": "https://api.bscscan.com",
                "api_keys": ["VNC1NCG47T8X1Y5HZ3NSKQX2USKVWR4ZUK"],
            },
        ],
    },
    {
        "chain_code": "heco",
        "shortname": "HECO",
        "fee_coin": "heco",
        "name": "Huobi ECO Chain",
        "chain_model": "account",
        "curve": "secp256k1",
        "chain_affinity": "eth",
        "qr_code_prefix": "heco",
        "bip44_coin_type": 60,
        "bip44_last_hardened_level": "ACCOUNT",
        "bip44_auto_increment_level": "ADDRESS_INDEX",
        "bip44_target_level": "ADDRESS_INDEX",
        "default_address_encoding": None,
        "chain_id": "128",
        "bip44_purpose_options": {},
        "fee_price_decimals_for_legibility": 9,
        "nonce_supported": True,
        "coins": [
            {
                "code": "heco",
                "symbol": "HT",
                "name": "Huobi ECO Chain",
                "decimals": 18,
                "icon": "https://onekey.243096.com/onekey/images/token/heco/HECO.png",
            }
        ],
        "clients": [
            {"class": "Geth", "url": "https://rpc.blkdb.cn/heco"},
            {"class": "Geth", "url": "https://heco1.onekey.so/rpc"},
            {"class": "Geth", "url": "https://http-mainnet-node.huobichain.com"},
            {"class": "BlockBook", "url": "https://heco1.onekey.so"},
            {
                "class": "Etherscan",
                "url": "https://api.hecoinfo.com",
                "api_keys": ["HDZRTIMGS873R25FCA8M7U96IIHJNNIBJD"],
            },
        ],
    },
    {
        "chain_code": "okt",
        "shortname": "OEC",
        "fee_coin": "okt",
        "name": "OKExChain Mainnet",
        "chain_model": "account",
        "curve": "secp256k1",
        "chain_affinity": "eth",
        "qr_code_prefix": "okt",
        "bip44_coin_type": 60,
        "bip44_last_hardened_level": "ACCOUNT",
        "bip44_auto_increment_level": "ADDRESS_INDEX",
        "bip44_target_level": "ADDRESS_INDEX",
        "default_address_encoding": None,
        "chain_id": "66",
        "bip44_purpose_options": {},
        "fee_price_decimals_for_legibility": 9,
        "nonce_supported": True,
        "coins": [
            {
                "code": "okt",
                "symbol": "OKT",
                "name": "OKExChain Mainnet",
                "decimals": 18,
                "icon": "https://onekey.243096.com/onekey/images/token/okt/OKT.png",
            }
        ],
        "clients": [{"class": "Geth", "url": "https://exchainrpc.okex.org"}],
    },
]
